### ISSUE TITLE
option to split long call

### ISSUE THREAD

**Issue by shalkya** [parmentelat/nbautoeval#32]
I'm already using PPrintCallRenderer to reduce the space taken with several keys from a dictionary. But I have a very long value, is there an option to cut it in parts (when displaying) ? I would like to avoid using `font_size='xx-small'`.

```
exo_rule_of_five = ExerciseFunction(
    test_rule_of_five,
    inputs_rule_of_five,
    call_renderer=PPrintCallRenderer(width=30, show_function=False),
    result_renderer=PPrintRenderer(width=30),
)
```

![image](https://user-images.githubusercontent.com/11618427/101056371-33c1d780-358b-11eb-9e0e-6461e5b66c5d.png)

**Comment by parmentelat** [comment]
hey

have you tried to also define `max_width=` like so
```
call_renderer=PPrintCallRenderer(max_width='200px', width=30, show_function=False)
```

the `width=` parameter is passed to Python's `pprint`, which unfortunately does not seem to be willing to be of assistance in this situation (although it could use parentheses and affixed strings, but well)

the `max_width=` will go to the html level; it might not be perfect wrt cut and paste'ing, but there's a chance it can help out in your case - I've mentioned 'px' to outline that it's a css thing, so of course ex or em should be fine too

in any case please let me know how it goes

**Comment by shalkya** [comment]
Thanks for your reply. Unfortunately it didn't work. 
I'm not sure what's wrong, but I tried to troubleshoot the code from `callrenderer.py` a bit.
```
        if self.max_width:
            print(result)
            result.add_layout({'max-width': f"{self.max_width}em"})
            print(result)
```
the output of both print is the same, would that be related to `max_width` not working ?

**Comment by parmentelat** [comment]
there's definitely something fishy in here; let me take a closer look

plus, at the very least, I was wrong above when I said that `max_width` could be set with any css unit, since the code that you outlined adds `em` to the mix

to be continued...

**Comment by parmentelat** [comment]
Hi

I confirm that `max-width` is properly passed to `ipywidgets.HTML` but that apparently has no effect...

I could manage a possible workaround like so :

```
exo_longargs = ExerciseFunction(
    longargs, inputs_longargs(),
    nb_examples=0,
    call_renderer=CallRenderer(
        show_function=False,
        css_properties={'word-wrap': 'break-word', 'max-width': '20em'},
        ))
``` 

probably not perfect, but can you try this out ?

**Comment by parmentelat** [comment]
for the record I have added a sample exercise named `longargs` that demonstrates this

**Comment by shalkya** [comment]
Hello
Thank you again. This method does work as intended.

As a side note, it seems that there is an issue with the notebook `exercise07-miscell`
At the 'display numpy arrays as images' part
I get the error `ModuleNotFoundError: No module named 'exercises.checkers'`
seems like it tries to load a file that doesn't exist anymore.
I can open a new issue for that one if you want.

**Comment by parmentelat** [comment]
> I can open a new issue for that one if you want.

no need, let's keep it simple, I had just forgotten to add this sample exercise to git, I just fixed it, thanks for the heads up :)
